-- SUPERSEDED as of build-log 0007. Kept only as a single-file historical
-- reference of the pre-migration-system schema shape -- no code reads
-- this file anymore. The authoritative, versioned schema now lives as
-- numbered files in state/migrations/, applied via
-- state/migration_runner.py. See state/migrations/001_initial.sql and
-- 002_inbox.sql for the current equivalent content.
